os: linux
root: false
language: node_js
node_js:
  node
services:
  - postgresql
before_script:
  - psql -c 'create database ecocalculator;' -U postgres
  - psql -f ./database/createDB.sql -d ecocalculator -U postgres
  - ip -c l
script: npm start
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//03ZTYCwDV2xplCgYIARAAGAMSNwF-L9IrBAUGos62rZ0X91UVicgmV6i6d4JjVKSMSi7ARY_IwIIP_IPd-J-5iiYAG1HJxMaUVJE"